app = "rainloop-app"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "youtous/rainloop:latest"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 8888
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

  [services.concurrency]
    hard_limit = 150
    soft_limit = 100
    type = "connections"

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[mounts]
  source = "data"
  destination = "/rainloop/data"