app = "ntfy-app"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  NTFY_BASE_URL = "https://nfty-web.fly.dev"
  NTFY_CACHE_FILE = "/nfty/cache.db"
  NTFY_CACHE_DURATION = "24h"
  NTFY_BEHIND_PROXY = "true"
  NTFY_ATTACHMENT_CACHE_DIR = "/nfty/attachments"
  NTFY_ATTACHMENT_TOTAL_SIZE_LIMIT = "5G"
  NTFY_ATTACHMENT_FILE_SIZE_LIMIT = "15M"
  NTFY_ATTACHMENT_EXPIRY_DURATION = "3h"
  NTFY_KEEPALIVE_INTERVAL = "45s"
  NTFY_MANAGER_INTERVAL = "6h"
  NTFY_VISITOR_ATTACHMENT_TOTAL_SIZE_LIMIT = "10M"
  NTFY_VISITOR_ATTACHMENT_DAILY_BANDWIDTH_LIMIT = "100M"
  NTFY_VISITOR_REQUEST_LIMIT_BURST = "60"
  NTFY_VISITOR_REQUEST_LIMIT_REPLENISH = "10s"
  NTFY_VISITOR_EMAIL_LIMIT_BURST = "16"
  NTFY_VISITOR_EMAIL_LIMIT_REPLENISH = "1h"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 80
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 150
    soft_limit = 100
    type = "connections"

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[mounts]
  source = "cache"
  destination = "/nfty"